name: First Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: print welcome
        run: echo "welcome to build"

      - name: print present working directory
        run: pwd
